name: Rust
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Check code format
      run: cargo fmt -- --check --verbose
    - name: Run clippy
      run: cargo clippy -- --forbid warnings
    - name: Run tests
      run: cargo test --verbose
